import type { Config } from "tailwindcss";

const config: Config & { safelist?: string[] } = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    'bg-success',
    'bg-success/90',
    'text-success-foreground',
    'bg-info',
    'bg-info/90',
    'text-info-foreground',
    'bg-error',
    'bg-error/90',
    'text-error-foreground',
    'bg-warning',
    'bg-warning/90',
    'text-warning-foreground',
    'bg-destructive',
    'bg-destructive/90',
    'text-destructive-foreground',
    'bg-secondary',
    'bg-secondary/80',
    'text-secondary-foreground',
    'bg-light',
    'bg-light/90',
    'text-light-foreground',
    'bg-dark',
    'bg-dark/90',
    'text-dark-foreground',
    // Alert colors
    'bg-emerald-50',
    'dark:bg-emerald-950/40',
    'text-emerald-900',
    'dark:text-emerald-50',
    'border-emerald-200',
    'dark:border-emerald-800/50',
    'bg-raspberry-red-50',
    'dark:bg-raspberry-red-950/40',
    'text-raspberry-red-900',
    'dark:text-raspberry-red-50',
    'border-raspberry-red-200',
    'dark:border-raspberry-red-800/50',
    'bg-lemon-lime-50',
    'dark:bg-lemon-lime-950/40',
    'text-lemon-lime-900',
    'dark:text-lemon-lime-50',
    'border-lemon-lime-200',
    'dark:border-lemon-lime-800/50',
    'bg-electric-aqua-50',
    'dark:bg-electric-aqua-950/40',
    'text-electric-aqua-900',
    'dark:text-electric-aqua-50',
    'border-electric-aqua-200',
    'dark:border-electric-aqua-800/50',
  ],
  theme: {
    extend: {
      fontFamily: {
        orbitron: ['var(--font-orbitron)', 'sans-serif'],
      },
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
          light: "var(--destructive-light)",
          dark: "var(--destructive-dark)",
          border: "var(--destructive-border)",
        },
        success: {
          DEFAULT: "var(--success)",
          foreground: "var(--success-foreground)",
        },
        warning: {
          DEFAULT: "var(--warning)",
          foreground: "var(--warning-foreground)",
        },
        info: {
          DEFAULT: "var(--info)",
          foreground: "var(--info-foreground)",
        },
        error: {
          DEFAULT: "var(--error)",
          foreground: "var(--error-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        light: {
          DEFAULT: "var(--light)",
          foreground: "var(--light-foreground)",
        },
        dark: {
          DEFAULT: "var(--dark)",
          foreground: "var(--dark-foreground)",
        },
        // Alert colors
        "emerald": {
          50: "var(--emerald-50)",
          100: "var(--emerald-100)",
          200: "var(--emerald-200)",
          500: "var(--emerald-500)",
          600: "var(--emerald-600)",
          800: "var(--emerald-800)",
          900: "var(--emerald-900)",
          950: "var(--emerald-950)",
        },
        "raspberry-red": {
          50: "var(--raspberry-red-50)",
          100: "var(--raspberry-red-100)",
          200: "var(--raspberry-red-200)",
          400: "var(--raspberry-red-400)",
          500: "var(--raspberry-red-500)",
          600: "var(--raspberry-red-600)",
          800: "var(--raspberry-red-800)",
          900: "var(--raspberry-red-900)",
          950: "var(--raspberry-red-950)",
        },
        "lemon-lime": {
          50: "var(--lemon-lime-50)",
          100: "var(--lemon-lime-100)",
          200: "var(--lemon-lime-200)",
          500: "var(--lemon-lime-500)",
          600: "var(--lemon-lime-600)",
          800: "var(--lemon-lime-800)",
          900: "var(--lemon-lime-900)",
          950: "var(--lemon-lime-950)",
        },
        "electric-aqua": {
          50: "var(--electric-aqua-50)",
          100: "var(--electric-aqua-100)",
          200: "var(--electric-aqua-200)",
          500: "var(--electric-aqua-500)",
          600: "var(--electric-aqua-600)",
          800: "var(--electric-aqua-800)",
          900: "var(--electric-aqua-900)",
          950: "var(--electric-aqua-950)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
};

export default config;
